web:
  host: "127.0.0.1"
  web_port: "8080"
  tls: false
  cert_private_path: ""
  cert_public_path: ""

database:
  type: "mysql" # mysql or sqlite
  path: ""      # sqlite path
  host: ""      # mysql host 
  port: ""
  name: ""
  user: ""
  pass: ""

user:
  cookie_timeout: 604800
  pass_hash_type: "md5" #密码哈希类型 text md5 
  def_avatar_save_path: "/data/avatar/" #头像保存的真实位置
  def_avatar_ginrouter_path: "/avatar/" #gin 路由的路径
  def_avatar_path: "/static/avatars/def.png"

warehouses:
  repos_per_page: 12      #每页显示多少个仓库
  repo_items_per_page: 10 #每个仓库的每页显示多少个物品


configed: false
